language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - PHPUNIT_FLAGS=""

matrix:
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.3
        - php: 7.4

before_install:
    - composer self-update

install:
    - composer install --prefer-source

script:
    - composer cs
    - composer static
    - composer validate --strict --no-check-lock
    - vendor/bin/phpunit $PHPUNIT_FLAGS
